# Generated by Django 5.0.14 on 2026-05-10 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("allow_hints", models.BooleanField(default=False)),
                ("randomize_questions", models.BooleanField(default=False)),
                ("sequential", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoringRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_penalty_after_n",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Penalty starts after this many wrong attempts. 1 = no free attempt.",
                    ),
                ),
                (
                    "attempt_penalty_per_mistake",
                    models.DecimalField(decimal_places=2, default="0.50", max_digits=4),
                ),
                (
                    "max_attempt_penalty",
                    models.DecimalField(decimal_places=2, default="1.50", max_digits=4),
                ),
                (
                    "time_penalty_threshold_minutes",
                    models.PositiveIntegerField(default=5),
                ),
                (
                    "time_penalty_per_minute",
                    models.DecimalField(decimal_places=2, default="0.25", max_digits=4),
                ),
                (
                    "max_time_penalty",
                    models.DecimalField(decimal_places=2, default="1.50", max_digits=4),
                ),
                (
                    "hint_penalty",
                    models.DecimalField(decimal_places=2, default="0.00", max_digits=4),
                ),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_rules",
                        to="scenarios.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("prompt", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_bonus", models.BooleanField(default=False)),
                (
                    "base_points",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                ("correct_answer", models.TextField()),
                ("choices", models.JSONField(blank=True, null=True)),
                ("hint", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("scenario", "order")},
            },
        ),
    ]
