# Generated by Django 5.0.14 on 2026-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome"),
                    ("moodle_imported", "Moodle Import Welcome"),
                    ("password_reset", "Password Reset"),
                    ("instance_created", "Instance Created"),
                    ("instance_results", "Instance Results"),
                    ("exam_start", "Exam Started"),
                    ("exam_complete", "Exam Completed"),
                    ("registration_open", "Registration Open"),
                    ("reminder", "Exam Reminder"),
                    ("custom", "Custom"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
