# Generated by Django 5.0.14 on 2026-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.TextField(
                        default="We are performing scheduled maintenance. We will be back shortly."
                    ),
                ),
                ("exam_global_paused", models.BooleanField(default=False)),
                ("moodle_base_url", models.URLField(blank=True, default="")),
                (
                    "moodle_token",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("smtp_host", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_user", models.CharField(blank=True, default="", max_length=255)),
                (
                    "smtp_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "smtp_from_email",
                    models.EmailField(
                        blank=True, default="noreply@kernelio.com", max_length=254
                    ),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Configuration",
            },
        ),
    ]
