# Generated by Django 5.0.14 on 2026-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
