# Generated by Django 5.0.14 on 2026-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0002_enrollment_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionattempt",
            name="first_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
