# Generated by Django 5.0.14 on 2026-05-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_fail", "Login Failed"),
                            ("login_ok", "Login Succeeded"),
                            ("logout", "Logout"),
                            ("permission_denied", "Permission Denied"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Changed"),
                            ("account_locked", "Account Locked"),
                            ("suspicious_request", "Suspicious Request"),
                            ("rate_limit", "Rate Limit Hit"),
                            ("super_admin_action", "Super-Admin Action"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "security log",
                "ordering": ["-created_at"],
            },
        ),
    ]
