# Generated by Django 5.0.14 on 2026-05-10 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("brand_name", models.CharField(default="KERNELiOS", max_length=120)),
                (
                    "site_title",
                    models.CharField(
                        default="KERNELiOS — Advanced Simulator", max_length=120
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("color_surface", models.CharField(default="#07080b", max_length=9)),
                ("color_primary", models.CharField(default="#ffd700", max_length=9)),
                (
                    "color_primary_glow",
                    models.CharField(default="#ffee58", max_length=9),
                ),
                ("color_secondary", models.CharField(default="#4b0082", max_length=9)),
                ("color_accent", models.CharField(default="#ff3d00", max_length=9)),
                ("color_foreground", models.CharField(default="#f4f4f5", max_length=9)),
                ("color_muted", models.CharField(default="#a1a1aa", max_length=9)),
                ("color_border", models.CharField(default="#27272a", max_length=9)),
                ("color_scrollbar", models.CharField(default="#ffd700", max_length=9)),
                ("logo_url", models.URLField(blank=True, default="")),
                (
                    "logo_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="brand-kits/logos/"
                    ),
                ),
                ("favicon_url", models.URLField(blank=True, default="")),
                ("email_header_logo_url", models.URLField(blank=True, default="")),
                (
                    "font_display_family",
                    models.CharField(default="Orbitron", max_length=120),
                ),
                ("font_display_url", models.URLField(blank=True, default="")),
                (
                    "font_display_file",
                    models.FileField(
                        blank=True, null=True, upload_to="brand-kits/fonts/"
                    ),
                ),
                ("font_body_family", models.CharField(default="Inter", max_length=120)),
                ("font_body_url", models.URLField(blank=True, default="")),
                (
                    "font_body_file",
                    models.FileField(
                        blank=True, null=True, upload_to="brand-kits/fonts/"
                    ),
                ),
                (
                    "font_mono_family",
                    models.CharField(default="JetBrains Mono", max_length=120),
                ),
                (
                    "country_codes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Comma-separated ISO country codes, e.g. "IL,US,DE"',
                        max_length=500,
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand_kits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
