# Generated by Django 5.0.14 on 2026-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branding", "0003_brandkit_uploads_and_per_kit_integrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandkit",
            name="footer_logo_url",
            field=models.URLField(
                blank=True, default="", help_text="Optional footer logo"
            ),
        ),
        migrations.AlterField(
            model_name="brandkit",
            name="logo_url",
            field=models.URLField(
                blank=True, default="", help_text="Main header logo URL"
            ),
        ),
    ]
