# Generated by Django 5.0.14 on 2026-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_seen_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
