# Generated by Django 5.0.14 on 2026-05-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="brand_kit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="branding.brandkit",
            ),
        ),
    ]
